"""Initial

Revision ID: de52c0873fdd
Revises: 
Create Date: 2026-09-25 12:21:44.503450
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'de52c0873fdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_state', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_last_seen_at'), 'cameras', ['last_seen_at'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('shift_start', sa.Time(), nullable=False),
    sa.Column('shift_end', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('consent_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_active'), 'employees', ['active'], unique=False)
    op.create_index(op.f('ix_employees_code'), 'employees', ['code'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('employee_code', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_path', sa.String(length=500), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_cam_ts', 'events', ['camera_id', 'ts'], unique=False)
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index('ix_events_emp_ts', 'events', ['employee_code', 'ts'], unique=False)
    op.create_index(op.f('ix_events_employee_code'), 'events', ['employee_code'], unique=False)
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('minutes_late', sa.Integer(), nullable=False),
    sa.Column('dwell_seconds', sa.Integer(), nullable=False),
    sa.Column('first_event_id', sa.String(length=36), nullable=True),
    sa.Column('last_event_id', sa.String(length=36), nullable=True),
    sa.Column('expected_status', sa.String(length=30), nullable=True),
    sa.Column('expected_leave_type', sa.String(length=30), nullable=True),
    sa.Column('has_exception', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_code'], ['employees.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code', 'day', name='uq_attendance_emp_day')
    )
    op.create_index(op.f('ix_attendance_day'), 'attendance', ['day'], unique=False)
    op.create_index('ix_attendance_day_status', 'attendance', ['day', 'status'], unique=False)
    op.create_index(op.f('ix_attendance_employee_code'), 'attendance', ['employee_code'], unique=False)
    op.create_index(op.f('ix_attendance_has_exception'), 'attendance', ['has_exception'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_has_exception'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_employee_code'), table_name='attendance')
    op.drop_index('ix_attendance_day_status', table_name='attendance')
    op.drop_index(op.f('ix_attendance_day'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_index(op.f('ix_events_employee_code'), table_name='events')
    op.drop_index('ix_events_emp_ts', table_name='events')
    op.drop_index(op.f('ix_events_camera_id'), table_name='events')
    op.drop_index('ix_events_cam_ts', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_employees_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_active'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_cameras_last_seen_at'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
